# Generated by Django 5.1.5 on 2026-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_add_served_kot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kot',
            name='served_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
