# Generated by Django 5.1.5 on 2026-07-10 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_vendor_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
