# Generated by Django 5.1.5 on 2026-07-11 02:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def normalize_units_and_backfill_payments(apps, schema_editor):
    Inventory = apps.get_model('app2', 'Inventory')
    PurchaseOrderItem = apps.get_model('app2', 'PurchaseOrderItem')
    PurchaseOrder = apps.get_model('app2', 'PurchaseOrder')
    PurchasePayment = apps.get_model('app2', 'PurchasePayment')
    unit_map = {'liters': 'liter', 'litres': 'liter', 'kgs': 'kg', 'gms': 'g', 'grams': 'g', 'pieces': 'piece'}
    for old, new in unit_map.items():
        Inventory.objects.filter(unit__iexact=old).update(unit=new)
        PurchaseOrderItem.objects.filter(unit__iexact=old).update(unit=new)
    for order in PurchaseOrder.objects.filter(amount_paid__gt=0):
        PurchasePayment.objects.get_or_create(
            purchase_order=order,
            amount=order.amount_paid,
            payment_date=order.payment_date or order.purchase_date,
            defaults={
                'payment_method': order.payment_method or 'cash',
                'reference_number': 'OPENING-' + order.number,
                'notes': 'Opening payment migrated from the original purchase record.',
                'created_by': order.created_by,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_merge_20260710_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('liter', 'Litres (L)'), ('ml', 'Millilitres (ml)'), ('piece', 'Pieces'), ('packet', 'Packets'), ('box', 'Boxes'), ('bottle', 'Bottles'), ('can', 'Cans'), ('dozen', 'Dozen')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('g', 'Grams (g)'), ('liter', 'Litres (L)'), ('ml', 'Millilitres (ml)'), ('piece', 'Pieces'), ('packet', 'Packets'), ('box', 'Boxes'), ('bottle', 'Bottles'), ('can', 'Cans'), ('dozen', 'Dozen')], max_length=50),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('credit', 'Credit')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app2.purchaseorder')),
            ],
            options={
                'ordering': ['payment_date', 'id'],
            },
        ),
        migrations.RunPython(normalize_units_and_backfill_payments, migrations.RunPython.noop),
    ]
