# Generated by Django 5.1.5 on 2026-07-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_alter_inventory_unit_alter_purchaseorderitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_returns', to='app2.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_returns', to='app2.vendor'),
        ),
    ]
